### ISSUE TITLE
Callback function not functioning as expected.

### ISSUE THREAD

**Issue by Shashoug** [pvsvamsi/SystemAlertWindow#63] opened 2021-06-12 16:19 UTC
Hello, at first thank you for saving our time to build such a great feature like this.

* PROBLEM:
 i tried to implement this package i went with the docs provided in your repo and pub.dev. 
the installation process was successful and the SystemAlertWindow is showing as expected, but when i try to click the button the SystemAlertWindow doesnt respond to my clicks.
when i tried to log things out this error appeared:
```
`../../FLUTTER%20ENGINE/flutter/.pub-cache/hosted/pub.dartlang.org/system_alert_window-0.5.0/lib/models/system_window_body.dart:19:49: Warning: Operand of null-aware operation '?.' has type 'EachRow' which excludes null.
 - 'EachRow' is from 'package:system_alert_window/models/system_window_body.dart' ('../../FLUTTER%20ENGINE/flutter/.pub-cache/hosted/pub.dartlang.org/system_alert_window-0.5.0/lib/models/system_window_body.dart').
          : List<dynamic>.from(rows!.map((x) => x?.getMap())),
                                                ^
../../FLUTTER%20ENGINE/flutter/.pub-cache/hosted/pub.dartlang.org/system_alert_window-0.5.0/lib/models/system_window_body.dart:41:52: Warning: Operand of null-aware operation '?.' has type 'EachColumn' which excludes null.
 - 'EachColumn' is from 'package:system_alert_window/models/system_window_body.dart' ('../../FLUTTER%20ENGINE/flutter/.pub-cache/hosted/pub.dartlang.org/system_alert_window-0.5.0/lib/models/system_window_body.dart').
          : List<dynamic>.from(columns!.map((x) => x?.getMap())),`

```
i want when the user click on the button, the app make Dio request and get value from sharedPrefs, but this error is produced:

`
 [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
i will list my code here:
Application.kt:
```
`package my_package_name


import android.app.Application
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import root.software.waydriver.LifecycleDetector
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
import `in`.jvapps.system_alert_window.SystemAlertWindowPlugin


class App : Application(),PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        registerActivityLifecycleCallbacks(LifecycleDetector.activityLifecycleCallbacks)
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
        SystemAlertWindowPlugin.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.flutter.plugins.firebasemessaging")) {
            FirebaseMessagingPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
        }
        SystemAlertWindowPlugin.registerWith(registry.registrarFor("in.jvapps.system_alert_window"));
    }

}
`
```
my MainActivity.kt:
```
`
public class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Notifications.createNotificationChannels(this)
    }

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        val binaryMessenger = flutterEngine.dartExecutor.binaryMessenger

        MethodChannel(binaryMessenger, "com.example/background_service").apply {
            setMethodCallHandler { method, result ->
                if (method.method == "startService") {
                    val callbackRawHandle = method.arguments as Long
                    BackgroundService.startService(this@MainActivity, callbackRawHandle)
                    result.success(null)
                } else {
                    result.notImplemented()
                }
            }
        }

        MethodChannel(binaryMessenger, "com.example/app_retain").apply {
            setMethodCallHandler { method, result ->
                if (method.method == "sendToBackground") {
                    moveTaskToBack(true)
                    result.success(null)
                } else {
                    result.notImplemented()
                }
            }
        }
    }
}`

```
i used to example code and paste it into my project just to make sure the implementation is successfull.
any help guys will be appreciated.

**Comment by pvsvamsi** [comment] 2021-06-18 06:43
Duplicate of #60

**Comment by pvsvamsi** [comment] 2021-06-18 06:43
Please add your comments under the original issue

**Closed** 2021-06-18 06:43 UTC
