### ISSUE TITLE
Call back not working

### ISSUE THREAD

**Issue by MRishiK99** [pvsvamsi/SystemAlertWindow#10] opened 2020-04-10 16:42 UTC
V/SystemAlertWindowPlugin(30292): invoking callback for tag focus_button
V/SystemAlertWindowPlugin(30292): Invoking on method channel

**Comment by MRishiK99** [comment] 2020-04-10 16:42
This is for most recent version!

**Comment by pvsvamsi** [comment] 2020-04-10 18:04
Callbacks are working on my end. Need full logs to assist any further (Clone example run and share the logs).

**Comment by MRishiK99** [comment] 2020-04-10 18:17
Yea sure thanks for the instant reply,

Here is the log for your example,

`Launching lib\main.dart on SM A505F in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        57.9s
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                        37.2s
D/FlutterActivity(21872): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(21872): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(21872): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(21872): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(21872): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@8985c09
D/FlutterActivityAndFragmentDelegate(21872): Executing Dart entrypoint: main, and sending initial route: /
D/SurfaceView(21872): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{eb8d63c V.E...... ......I. 0,0-0,0} of ViewRootImpl@d913910[MainActivity]
D/ViewRootImpl@d913910[MainActivity](21872): Relayout returned: old=[0,0][1080,2340] new=[0,0][1080,2340] result=0x7 surface={true 489057140736} changed=true
I/OpenGLRenderer(21872): Initialized EGL, version 1.4
D/OpenGLRenderer(21872): Swap behavior 2
D/mali_winsys(21872): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(21872): eglCreateWindowSurface = 0x71de19b180, 0x71de13c010
D/SurfaceView(21872): show() Surface(name=SurfaceView - com.example.temp/com.example.temp.MainActivity@eb8d63c@0[21872])/@0x461afc5 io.flutter.embedding.android.FlutterSurfaceView{eb8d63c V.E...... 
......ID 0,0-1080,2214}
D/SurfaceView(21872): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{eb8d63c V.E...... ......ID 0,0-1080,2214}
D/mali_winsys(21872): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView(21872): surfaceChanged (1080,2214) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{eb8d63c V.E...... ......ID 0,0-1080,2214}
D/ViewRootImpl@d913910[MainActivity](21872): Relayout returned: old=[0,0][1080,2340] new=[0,0][1080,2340] result=0x3 surface={true 489057140736} changed=false
D/ViewRootImpl@d913910[MainActivity](21872): MSG_RESIZED: frame=[0,0][1080,2340] ci=[0,83][0,126] vi=[0,83][0,126] or=1
D/ViewRootImpl@d913910[MainActivity](21872): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(21872): prepareNavigationBarInfo() DecorView@756137[MainActivity]
D/InputMethodManager(21872): getNavigationBarColor() -855310
D/InputMethodManager(21872): prepareNavigationBarInfo() DecorView@756137[MainActivity]
D/InputMethodManager(21872): getNavigationBarColor() -855310
V/InputMethodManager(21872): Starting input: tba=com.example.temp ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(21872): startInputInner - Id : 0
I/InputMethodManager(21872): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(21872): Input channel constructed: fd=95
D/InputMethodManager(21872): prepareNavigationBarInfo() DecorView@756137[MainActivity]
D/InputMethodManager(21872): getNavigationBarColor() -855310
V/InputMethodManager(21872): Starting input: tba=com.example.temp ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(21872): startInputInner - Id : 0
D/SystemAlertWindowPlugin(21872): onClickCallBackHandle 3292043634672398676
I/SystemAlertWindowPlugin(21872): Unable to start callBackHandle... as plugin is not registered
Syncing files to device SM A505F...                                     
D/ViewRootImpl@d913910[MainActivity](21872): ViewPostIme pointer 0
Syncing files to device SM A505F...
D/ViewRootImpl@d913910[MainActivity](21872): ViewPostIme pointer 1
Syncing files to device SM A505F...
D/SystemAlertWindowPlugin(21872): Going to show System Alert Window
Syncing files to device SM A505F...
D/WindowService(21872): Received - Start work
Syncing files to device SM A505F...
D/WindowService(21872): Creating Window Service
Syncing files to device SM A505F...
D/WindowService(21872): Starting the service process
Syncing files to device SM A505F...
I/WindowService(21872): Intent extras are not null
Syncing files to device SM A505F...
D/WindowService(21872): Ending the service process
Syncing files to device SM A505F...
E/WindowService(21872): view not found
Syncing files to device SM A505F...
D/WindowService(21872): Creating the window
Syncing files to device SM A505F...
D/InputTransport(21872): Input channel constructed: fd=102      
Syncing files to device SM A505F...
D/ViewRootImpl@ce24764[](21872): setView = android.widget.LinearLayout{9710dcd V.E...... ......ID 0,0-0,0} TM=true MM=false
Syncing files to device SM A505F...
D/ViewRootImpl@ce24764[](21872): Relayout returned: old=[0,83][1080,2214] new=[0,608][1080,1211] result=0x7 surface={true 489505980416} changed=true
Syncing files to device SM A505F...
D/mali_winsys(21872): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
Syncing files to device SM A505F...
D/OpenGLRenderer(21872): eglCreateWindowSurface = 0x71ddc1d980, 0x71f8d48010
Syncing files to device SM A505F...                                                                D/ViewRootImpl@ce24764[](21872): MSG_RESIZED: frame=[0,608][1080,1211] ci=[0,0][0,0] vi=[0,0][0,0] or=1
Syncing files to device SM A505F...                                                                 9,006ms (!)

�🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on SM A505F is available at:
http://127.0.0.1:51134/9ivrrLzkDwU=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
D/ViewRootImpl@ce24764[](21872): ViewPostIme pointer 0
D/ViewRootImpl@ce24764[](21872): ViewPostIme pointer 1
D/SystemAlertWindowPlugin(21872): onClickCallBackHandle 3292043634672398676
V/SystemAlertWindowPlugin(21872): invoking callback for tag focus_button
V/SystemAlertWindowPlugin(21872): Invoking on method channel
D/ViewRootImpl@ce24764[](21872): ViewPostIme pointer 0
D/ViewRootImpl@ce24764[](21872): ViewPostIme pointer 1
V/SystemAlertWindowPlugin(21872): invoking callback for tag focus_button
V/SystemAlertWindowPlugin(21872): Invoking on method channel`


As you can see the callback function is not executed. The actual output must have been "Focus button has been called" right??

**Comment by MRishiK99** [comment] 2020-04-10 18:19
Also i tried this on another phone btw

**Comment by pvsvamsi** [comment] 2020-04-11 16:46
Yes "Focus button has been called" should have been printed. Can you open Logcat in Android Studio (open any other android project), put "system_alert_window" in the search and then click on any button. Then post the logs here.

**Comment by pvsvamsi** [comment] 2020-04-14 05:09
@MRishiK99 Closing this issue, as there is no reply from your end. Hope the issue is fixed. Please reopen the issue, if the it still persists.

**Closed by pvsvamsi** 2020-04-14 05:09 UTC
Labels: waiting for reply
